name: linter-check
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
    -  name: install of dependency
       run:
         pip install poetry
         make install
    -  name: linter-check
       run:
         make lint