name: linter
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  linter-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    -  name: install of dependency
       run: |
         pip install poetry
         make install
    -  name: linter-check
       run: |
         make lint